
--
-- TOC entry 216 (class 1259 OID 24577)
-- Name: task; Type: TABLE; Schema: public; Owner: sconde
--

CREATE TABLE public.task (
    id bigint NOT NULL,
    description text,
    done boolean,
    title character varying(255),
    created_at date,
    updated_at date
);


ALTER TABLE public.task OWNER TO sconde;

--
-- TOC entry 215 (class 1259 OID 24576)
-- Name: task_id_seq; Type: SEQUENCE; Schema: public; Owner: sconde
--

ALTER TABLE public.task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 32769)
-- Name: users; Type: TABLE; Schema: public; Owner: sconde
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    username character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO sconde;

--
-- TOC entry 217 (class 1259 OID 32768)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: sconde
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4903 (class 0 OID 24577)
-- Dependencies: 216
-- Data for Name: task; Type: TABLE DATA; Schema: public; Owner: sconde
--

COPY public.task (id, description, done, title, created_at, updated_at) FROM stdin;
10	Je dois effectuer mes cinq prierres obligatoires.	f	Prierre	2025-04-15	2025-04-15
8	Il s'agit de préparer le repas pour moi-même et pour ma compagne, en prenant soin de choisir et de préparer des plats que nous apprécierons ensemble. Cela implique de cuisiner les ingrédients nécessaires, de dresser la table et de créer un moment agréable pour partager un bon repas à deux.	t	Cusine	2025-04-15	2025-04-15
6	Il est nécessaire de nettoyer les vêtements ainsi que les chaussures qui sont sales, en les lavant soigneusement pour éliminer toute la saleté et les taches qu'ils ont accumulées. Pour les habits, il faudra les mettre en machine ou les laver à la main, tandis que pour les chaussures, il faudra peut-être les brosser ou les nettoyer en fonction du matériau.	t	Lessive	2025-04-15	2025-04-15
7	Il faut utiliser l'aspirateur pour nettoyer le sol, ensuite balayer les endroits qui n'ont pas été atteints par l'aspirateur, et enfin passer la serpillère pour laver et donner un coup de frais à toute la surface.	t	Ménage	2025-04-15	2025-04-15
5	Il faut nettoyer tous les ustensiles de cuisine utilisés, tels que les couteaux, les casseroles, les poêles, les planches à découper, les spatules et les cuillères. Cela implique de les rincer, les frotter avec de l'eau chaude et du savon, puis de les sécher soigneusement pour les remettre en ordre et les rendre prêts à être utilisés à nouveau.	f	Vaisselle	\N	2025-04-15
11	Test description	f	Test	2025-04-15	2025-04-15
12	Test	f	Test	2025-04-15	2025-04-15
9	Je dois faire du vélo pendant 20 minutes.	f	Sport	\N	2025-04-15
14	Je dois préparer mes entretiens de façon méthodique et efficace.	f	Préparation Entretien	2025-04-22	2025-04-22
15	Test	f	Test	2025-04-26	2025-04-26
16	Test	f	Test	2025-04-26	2025-04-26
\.


--
-- TOC entry 4905 (class 0 OID 32769)
-- Dependencies: 218
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: sconde
--

COPY public.users (id, password, role, username) FROM stdin;
3	$2a$10$hlfPl/wj7SdtNEkApRkHtO92aRrcPEi6IU81bGrgQXMZ3VnvNrleC	USER	sconde
4	$2a$10$iMMQvA21ZANqKIf0jodo3.leRuP9I5T/j6/FTcV7NQp9l8WF6/qem	USER	hawa
\.


--
-- TOC entry 4911 (class 0 OID 0)
-- Dependencies: 215
-- Name: task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sconde
--

SELECT pg_catalog.setval('public.task_id_seq', 16, true);


--
-- TOC entry 4912 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sconde
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- TOC entry 4754 (class 2606 OID 24581)
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: sconde
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (id);


--
-- TOC entry 4756 (class 2606 OID 32776)
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: sconde
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 4758 (class 2606 OID 32774)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: sconde
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


-- Completed on 2025-05-28 16:18:21

--
-- PostgreSQL database dump complete
--

